const number1 = 5;
const number2 = 3;
const product = number1 * number2;
console.log('value of product: ' + product);
console.log('type of product: ' + typeof product);
const charge = 5;
const payment = 3;
const amountRemaining = charge - payment;
console.log('value of amountRemaining: ' + amountRemaining);
console.log('type of amountRemaining: ' + typeof amountRemaining);
const tests = 100;
const assignments = 90;
const final = 70;
const grade = (tests + assignments + final) / 3;
console.log('value of grade: ' + grade);
console.log('type of grade: ' + typeof grade);
const firstName = 'Eric';
const lastName = 'Fried';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName: ' + fullName);
console.log('type of fullName: ' + typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic: ' + isAcidic);
console.log('type of isAcidic: ' + typeof isAcidic);
const numberOfSoldiers = 600;
const isSparta = numberOfSoldiers === 300;
console.log('value of isSparta: ' + isSparta);
console.log('type of isSparta: ' + typeof isSparta);
let nickname = fullName;
nickname = fullName + ' is the GOAT';
console.log('value of nickname: ' + nickname);
console.log('type of nickname: ' + typeof nickname);
